// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcPhone.Data;

#nullable disable

namespace MvcPhone.Migrations
{
    [DbContext(typeof(MvcPhoneContext))]
    [Migration("20240328231005_AddIm")]
    partial class AddIm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("MvcMovie.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Phone");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Color = "Silver",
                            Name = "iPhone 14 Pro Max",
                            Price = 1099.01m
                        },
                        new
                        {
                            Id = 11,
                            Color = "Lavender",
                            Name = "Samsung Galaxy S23 Ultra",
                            Price = 1188.02m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
