// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Models;
using MvcPhone.Data;

public class Decimal18Converter : ValueConverter<decimal, decimal>
{
    public Decimal18Converter() : base(v => Math.Round(v, 2), v => v)
    { }
}

